### ISSUE TITLE
Bug Rails 3.2 ao executar migrações pela primeira vez

### ISSUE THREAD

**Issue by tacsio** [redu/redu#1721]
Log:

```
Mysql2::Error: Table 'redu_development.course_enrollments' doesn't exist: SHOW FULL FIELDS FROM `course_enrollments`
```

Dei uma olhada básica e acredito que o erro esteja relacionado as "instruções" de scopes em alguns modelos.

Ex.:
app/models/user_course_association.rb

``` ruby
 scope :approved, where(:state => 'approved')
```

Um modo de resolver(Eu não sei se é o ideal) é colocar o bloco do scope dentro de bloco lambda

``` ruby
 scope :approved, lambda { where(:state => 'approved') } 
```

**Comment by fltiago** [comment]
@tacsio esse repositório foi movido para https://github.com/OpenRedu/OpenRedu , não sei o motivo, mas tu pode perguntar para: @Bouckaert

**Comment by tacsio** [comment]
Ok, @fltiago 

Acho esqueceram de atualizar as referências no site após migrar!
:sweat_smile:
